blank_issues_enabled: true
contact_links:
  - name: Question about consuming Open Misconceptions
    url: https://github.com/open-misconceptions/miscon-data/discussions
    about: Ask how to use the JSON, CASE or diagnosis formats.
